### ISSUE TITLE
Scroll Bug [Site]

### ISSUE THREAD

**Issue by xRoBoTx** [PolyMC/polymc.github.io#203]

**Comment by Scrumplex** [comment]
Seems to be specific to Windows

**Comment by TayouVR** [comment]
can confirm, happens for me too
![image](https://user-images.githubusercontent.com/31988415/182479231-44d90b81-1247-422d-ba26-6a0536b4c1a4.png)

Not sure whats causing it, it doesn't highlight anything...
I also tried to use "Responsive Design mode" to play around with user agent and such, but in that mode I couldn't reproduce the issue at all.

Explicitly setting `overflow: hidden;` for the CSS properties seems to "resolve" it though. (until someone with a 200 character username comes along, that would need scrolling...)

Don't think I can generate such a neat table, but uh:
OS: Windows 10 21H2 (19044.1826)
Browser: Mozilla Firefox 103.0 (64-bit)
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:103.0) Gecko/20100101 Firefox/103.0

**Comment by xRoBoTx** [comment]
That should fix this issue. Replaced `overflow-y: scroll` to `auto`.
```css
.user-name {
    color: #fff;
    font-size: 1.2em;
    overflow-y: auto;
    overflow-wrap: break-word;
    text-align: center;
}
```
